[project]
name = "ai-agent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.7.2",
    "langchain-community>=0.4.1",
    "python-dotenv>=1.1.1",
    "tavily-python>=0.7.17",
]
